version: "3"

services:
  php:
    build:
      context: .
    container_name: cps_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ${DOCKER_PHP_LOG_DIR}:/var/log/php
      - /usr/local/etc/php:/usr/local/etc/php
    ports:
      - "8000:8000"
      - "9090:9000"
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Shanghai

    depends_on:
      - mysql
      - redis
    privileged：true

  nginx:
    container_name: cps_nginx
    build:
      context: ./docker/nginx
    volumes:
      - /etc/nginx:/etc/nginx
      - ${DOCKER_NGINX_LOG_DIR}:/var/log/nginx
      - ./:/var/www
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - php

  redis:
    image: redis:alpine
    container_name: cps_redis
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:5.7
    container_name: cps_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravue
      MYSQL_USER: laravue
      MYSQL_PASSWORD: laravue
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
    external: false
