version: "3"
services:
  php:
    build: ./php/
    volumes:
      - /usr/local/nginx/www:/data/www/
      - /usr/local/php/conf/:/usr/local/etc/
    ports:
      - "9000:9000"
  nginx:
    build: ./nginx/
    volumes:
      - /usr/local/nginx/conf/conf.d/:/etc/nginx/conf.d
      - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/log:/data/log/nginx
      - /usr/local/nginx/www:/data/www
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - php:php-fpm
  mysql
    build: ./mysql/
    volumes:
      - /usr/local/nginx/mysql/conf/:/etc/mysql/
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - php:php-fpm
